#
# Makefile.lib for arch/c6x
#
# Extra stuff for each arch/c6x/<dir>'s makefile
# [To bad scripts/Makefile.lib does not look for sucha file as this and inlcude it]
#

quiet_cmd_as_o_S64 = AS-TI $(strip $(quiet_modtag))  $@
cmd_as_o_S64       = $(CC) -D__ASSEMBLY__ $(KBUILD_AFLAGS) -traditional -x assembler -c -o $@ $< ; \
	echo "$@: $<" >$(depfile)

%.o: %.S64 FORCE
	$(call if_changed_dep,as_o_S64)

