#
# Makefile for arch/c6x/drivers/
#

obj-$(CONFIG_CIO_CONSOLE)      += cio/

obj-$(CONFIG_PLL_C6X)          += pll.o
obj-$(CONFIG_GPIO_C6X)         += gpio.o
obj-$(CONFIG_TMS320C64XPLUS)   += tsc-c64xplus.o
obj-$(CONFIG_TMS320C66X)       += tsc-c64xplus.o
obj-$(CONFIG_TIMER_C6X)        += timer.o
obj-$(CONFIG_INTC_C64XPLUS)    += intc-c64xplus.o
obj-$(CONFIG_CP_INTC)          += cp-intc.o

obj-$(CONFIG_TMS320C64X_GEMAC) += gemac.o mdio.o
obj-$(CONFIG_SGMII)            += sgmii.o


obj-$(CONFIG_RAPIDIO_TCI648X)  += rio-tci648x.o
obj-$(CONFIG_I2C_DAVINCI)      += i2c.o
obj-$(CONFIG_EDMA3)            += edma.o

obj-$(CONFIG_MCBSP)            += mcbsp.o
obj-$(CONFIG_MCBSP_UART)       += mcbsp-uart.o

obj-$(CONFIG_IPC)              += ipc/
