#
# Makefile for arch/c6x/drivers/
#

obj-$(CONFIG_HPI_CONSOLE)      += cio/

obj-$(CONFIG_PLL_TCI648X)      += pll-tci648x.o
obj-$(CONFIG_TMS320C64XPLUS)   += tsc-c64xplus.o
obj-$(CONFIG_TIMER_TCI648X)    += timer-tci648x.o

obj-$(CONFIG_TMS320C64X_GEMAC) += gemac.o gmdio.o
obj-$(CONFIG_TMS320C6X_EMAC)   += emac.o mdio.o
obj-$(CONFIG_SGMII)            += sgmii.o

obj-$(CONFIG_RAPIDIO_TCI648X)  += rio-tci648x.o
obj-$(CONFIG_I2C_DAVINCI)      += i2c.o
obj-$(CONFIG_EDMA3)            += edma.o

obj-$(CONFIG_MCBSP)            += mcbsp.o
obj-$(CONFIG_MCBSP_UART)       += mcbsp-uart.o
