#
# Makefile for drivers/platform/keystone
#

# Multicore Navigator drivers
obj-$(CONFIG_TI_KEYSTONE_PA)     += pa.o
obj-$(CONFIG_TI_KEYSTONE_QM)     += qmss.o
obj-$(CONFIG_TI_KEYSTONE_PKTDMA) += pktdma.o

# NetCP additional drivers
obj-$(CONFIG_TI_KEYSTONE_CPSW)   += cpsw.o
obj-$(CONFIG_TI_KEYSTONE_SGMII)	 += sgmii.o

# RapidIO drivers
obj-$(CONFIG_TI_KEYSTONE_RAPIDIO) += rio.o

# PCIe drivers
obj-$(CONFIG_TI_KEYSTONE_PCIE)   += pcie.o
