#
# Makefile for drivers/platform/keystone
#

obj-$(CONFIG_TI_KEYSTONE_PA)     += pa.o
obj-$(CONFIG_TI_KEYSTONE_QM)     += qmss.o
obj-$(CONFIG_TI_KEYSTONE_PKTDMA) += pktdma.o
obj-$(CONFIG_TI_KEYSTONE_CPSW)   += cpsw.o
obj-$(CONFIG_TI_KEYSTONE_SGMII)	 += sgmii.o
